### PR TITLE
Set up a 'Hello Microverse' project

### PR DESCRIPTION
**Pull request by chelobotix**
Dear code reviewer.
I would be very grateful if you could review my code.
I will be looking forward to your reply
Thank you

### CODE REVIEW

**Review by nedjwab — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi @chelobotix 

Nice job, you are almost there.



## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.

## (Changes Required) Aspects to improve: ♻️
You did great implementing some of the project requirements, but you still have some issues: 
 `[ ]  Pull Request should have a descriptive title telling you what changes are inside.(example: Set up a 'Hello Microverse' project). kindly fix that 🤓.`
 
## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by chelobotix** [comment]
Dear @nedjwab thank you for your quick reply.
I have changed the title of the pull request as you suggested to me.
I look forward to your comments
Cheers

**Review by MaganaAsiati — CHANGES_REQUESTED** [review]
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @chelobotix , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

so-close-gif-4

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

- [ ] You did great by adding the description to your pull request but kindly  Add a meaningful description that gives more information about what you did implement in the current milestone you are working on :heavy_check_mark:👨🏻‍💻

here below example 

image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] [OPTIONAL] KIndly add more information about the  author in your readme file  and add more sections it will make your readme look more professional:+1: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by chelobotix** [comment]
In this PR, I fulfilled the following tasks:
- [x] Create a new GitHub repository.
- [x] Create a new Branch according to the [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow) rules.
- [x] Added a [.gitignore ](https://github.com/chelobotix/Hello-Micorverse/blob/feature_1/.gitignore)file.
- [x] Set up a [Linter](https://github.com/microverseinc/linters-config/tree/master/html-css) for Html and Css and make sure that any files that are not relevant are ignored by git.
- [x] Added a descriptive README file
- [x] Added a Html file ([index.html](https://github.com/chelobotix/Hello-Micorverse/blob/feature_1/index.html)) that includes a header with the text "Hello Microverse" 
- [x] Added a Css file ([style.css](https://github.com/chelobotix/Hello-Micorverse/blob/feature_1/style.css)) that includes one class with style for the header (color: `#0b71ac`)
- [x] Added test.md file with the text "The file should be ignored by git"

**Comment by chelobotix** [comment]
Dear @MaganaAsiati, I have implemented the changes you kindly suggested to me.
- [x] Add a comment with an extensive description of what changes were implemented
- [x] update de readme.md file with the new section "File" and more information about the author

Thank you

**Review by christianbiring1 — APPROVED** [review]
Hi @chelobotix , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
nicee

## Highlights
- [ ] All changes were implemented :muscle: 
## Optional suggestions
- [ ] Kindly make sure on the following milestone, you write the summary of your Pull Request in this box you use to address to the reviewer. You do not need to address the reviewer in that section. :rocket: 
image

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
